### ISSUE TITLE
如果开辟一个字节的大小内存，似乎会有

### ISSUE THREAD

**Issue by irvin12** [fananchong/aoi#1]
![image](https://user-images.githubusercontent.com/10721476/67373303-fd591100-f5b1-11e9-8f5e-2f470908d522.png)
如果需要开辟的内存小于指针内存的大小，会导致指针存放的地址不完整，引起越界。
改成链表指针，另外开辟地址保存如何。如下：
![image](https://user-images.githubusercontent.com/10721476/67373540-680a4c80-f5b2-11e9-9f1d-d4894e79ff40.png)

**Comment by fananchong** [comment]
本库要分配的元素：
``` c++
using TNode = QuadTreeNode<TItem, NodeCapacity, LevelLimit>
```
一定大于 1 ，放心使用。 用链表实现上会稍复杂点，缺多浪费内存等问题
